Many new facilities

diff --git a/trunk/nuweb/Makefile b/trunk/nuweb/Makefile
--- a/trunk/nuweb/Makefile
+++ b/trunk/nuweb/Makefile
@@ -1,9 +1,9 @@
 CC = cc
 
-CFLAGS = -O -g
+CFLAGS = -g
 
 TARGET = nuweb
-VERSION ?= $(shell date +%Y%m%d)
+VERSION = 1.0b1
 
 OBJS = main.o pass1.o latex.o html.o output.o input.o scraps.o names.o \
 	arena.o global.o
@@ -15,21 +15,21 @@ HDRS = global.h
 
 DIST = Makefile README *.bib *.sty nuweb.w nuwebsty.w \
 		$(TARGET)doc.tex $(SRCS) $(HDRS)
-
+ 
 
 .SUFFIXES: .dvi .tex .w .hw
 
 .w.tex:
-	./nuweb $*.w
+	nuweb $*.w
 
 .hw.tex:
-	./nuweb $*.hw
+	nuweb $*.hw
 
 .tex.dvi:
 	latex ./$*.tex
 
 .w.dvi:
-	./nuweb $*.w
+	nuweb $*.w
 	latex ./$*.tex
 
 all:
@@ -42,14 +42,7 @@ shar:	$(TARGET)doc.tex
 tar:	$(TARGET)doc.tex
 	tar -cf $(TARGET)$(VERSION).tar $(DIST)
 
-distribution: all shar tar nuwebhtml nuwebdoc
-
-upload:
-	scp -r nuweb$(VERSION).sh nuweb$(VERSION).tar \
-		nuweb.ps nuwebdoc.ps \
-		nuwebdoc nuwebhtml \
-		nuweb.w \
-		mengel@nuweb.sourceforge.net:nuweb/htdocs
+distribution: all shar tar nuwebhtml nuwebdoc 
 
 nuwebdoc: nuwebdoc.tex
 	-latex nuwebdoc
@@ -66,9 +59,24 @@ nuwebhtml: nuweb
 	-nuweb nuwebhtml.hw
 	-latex nuwebhtml.tex
 	latex2html -split 0 nuwebhtml.tex
-
+	
 $(TARGET)doc.tex:	$(TARGET).tex
 	sed -e '/^\\ifshowcode$$/,/^\\fi$$/d' $(TARGET).tex > $@
+
+check: nuweb
+	@declare -i n=0; \
+        declare -i f=0; \
+	for i in test/*/*.sh ; do \
+	echo "Testing $$i"; \
+	sh $$i; \
+	if test $$? -ne 0; \
+	then echo "         $$i failed" ; \
+	f+=1; \
+	fi; \
+	n+=1; \
+	done; \
+        echo "$$n done"; \
+        echo "$$f failed"
 
 clean:
 	-rm -f *.o *.tex *.log *.dvi *~ *.blg *.lint
@@ -82,7 +90,7 @@ view:	$(TARGET).dvi
 print:	$(TARGET).dvi
 	lpr -d $(TARGET).dvi
 
-lint:
+lint:	
 	lint $(SRCS) > nuweb.lint
 
 $(OBJS): global.h
